Simplify MakeFile use
1. use braces to isolate changing directory so it can
be used from root directory
2. add `view-guide` option to workaround error when
using `watch-guide`
```
RuntimeError: no acceptor (port is in use or requires root privileges)
  ... .rvm/gems/ruby-2.7.3/gems/eventmachine-1.2.7/lib/eventmachine.rb:531:in `start_tcp_server'
 ```